### ISSUE TITLE
Scaling the number of instructions

### ISSUE THREAD

**Issue by zwhe99** [yizhongw/self-instruct#5]
Hi~

Why limit the number of instructions to 52K? Will the model be better if we have more instructions?

**Comment by yizhongw** [comment]
Hi @zwhe99 it's more because we observed the generation of novel tasks slows down after 52K. We also observed the fine-tuning performance plateaus at this size based on our limited experiments on SuperNI and the new user-oriented evaluation set. I think future work can benefit from a larger seed set with more diversified formats.

**Comment by zwhe99** [comment]
I see. Thanks for the response!
