### ISSUE TITLE
How to support chinese?

### ISSUE THREAD

**Issue by AISuperMa** [yizhongw/self-instruct#8]

**Comment by hujunchao** [comment]
same question

**Comment by xianbin7** [comment]
same question

**Comment by yizhongw** [comment]
Do you mean generating instruction data in Chinese? I think this is doable by changing the prompts and seed tasks into Chinese. Someone also did translation for the Alpaca instruction data directly [link](https://github.com/hikariming/alpaca_chinese_dataset). I don't have the bandwidth to support this in this repo though.

**Comment by FrackinFamous** [comment]
I heard whisper is very good at recognizing and translating as well so you
could take in voice prompts and convert to English before the query. Or use
a second model or separate call to translate the prompt then translate the
completion back. Extra steps but worth it is you can greatly improve
performance. AzureAI is really good at voice and translation as well. Makes
since since Azure has been providing infrastructure for some time.
